//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZerosAndHashtags.Resources.Colormaps {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enemy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enemy() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZerosAndHashtags.Resources.Colormaps.Enemy", typeof(Enemy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OO1111OOO117711O11700711177007711770077111700711O117711OOO1111OO.
        /// </summary>
        internal static string BasicEye {
            get {
                return ResourceManager.GetString("BasicEye", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O666666O666666666666666665566556655665566666666666666666O666666O.
        /// </summary>
        internal static string BasicSlime {
            get {
                return ResourceManager.GetString("BasicSlime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OO9OO9OOOO91O911O199991O9999999999399399O999999OOO9999OO11O991O1.
        /// </summary>
        internal static string Bat {
            get {
                return ResourceManager.GetString("Bat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OO1111OOO11FF11O11FFFF111FF00FF11FF00FF111FFFF11O11FF11OOO1111OO.
        /// </summary>
        internal static string BlueEye {
            get {
                return ResourceManager.GetString("BlueEye", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O8FFFF8O888FF888F888888B88B888BB8BBB88BBOC1CC1CO15555551O155551O.
        /// </summary>
        internal static string BlueMushroom {
            get {
                return ResourceManager.GetString("BlueMushroom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O444444O444444444444444448844884488448844444444444444444O444444O.
        /// </summary>
        internal static string BlueSlime {
            get {
                return ResourceManager.GetString("BlueSlime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O4444443O464464333D44D333AA44AA33AA11AA33AAAAAA34A1111A4O444444O.
        /// </summary>
        internal static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OOOOOOOOOOOO555OOOOO5O5OOOO53OOOOO030AOOOO131AOOOOAA33OOOOOAAOOO.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OOOOOOOOOOOOOOOOOOOOOOOOOOOOAOOOOO3A355OO553355OA55AAAA33A333AAA.
        /// </summary>
        internal static string LavaSlime {
            get {
                return ResourceManager.GetString("LavaSlime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 3A1CC1A3AA1CC1AA11CCCC11CCCCCCCC595959595C5C5C5CCCCCCCCCCCCCCCCC.
        /// </summary>
        internal static string Mimic {
            get {
                return ResourceManager.GetString("Mimic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OO1111OOO11AA11O11A00A111AA00AA11AA00AA111A00A11O11AA11OOO1111OO.
        /// </summary>
        internal static string RedEye {
            get {
                return ResourceManager.GetString("RedEye", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O311113O33311331333333111333133111333333O919919O12222221O122221O.
        /// </summary>
        internal static string RedMushroom {
            get {
                return ResourceManager.GetString("RedMushroom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O111111O11111111133113311331133111111111111OO111O111111OO1O11O1O.
        /// </summary>
        internal static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O5CCCC5O5C5555C555CCCC55C555555CCCCCCCCCCB4CC4BCCCCCCCCC0CCCCCC0.
        /// </summary>
        internal static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1773377177355377AA7337AA1AA11AA11111111111AAAA111AA00AA1OA1111AO.
        /// </summary>
        internal static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
    }
}
